services:
  www:
    build:
      dockerfile: ./dockerfile.www
    volumes:
      - "./oscilla:/app/oscilla"
      - "./db:/app/db"
      - "./docker/www/prestart.sh:/app/prestart.sh"
    ports:
      - "80:80"
    environment:
      IS_DEV: true
      RELOAD: true
      DATABASE_URL: postgresql://main:main12345@db/main
      CACHE_REDIS_HOST: redis
      CACHE_REDIS_PORT: 6379
    depends_on:
      - db
      - redis

  redis:
    image: redis

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: main12345
      POSTGRES_USER: main
      POSTGRES_DB: main

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
