apiVersion: oscilla/v1
kind: Enemy
metadata:
  name: iron-golem
spec:
  displayName: "Iron Golem"
  description: "Massive construct that hits very hard."
  stats:
    hp: 9999
    attack: 50
    defense: 10
  on_defeat_effects:
    - type: stat_change
      stat: xp
      amount: 100
  loot:
    - entries:
        - item: test-widget
          weight: 1
