apiVersion: oscilla/v1
kind: Location
metadata:
  name: and-condition
spec:
  displayName: "AND Condition Test"
  description: "Test complex condition evaluation."
  region: conditions
  adventures:
    - ref: and-condition
      weight: 100
