"""normalize iteration_id column type

Revision ID: 10ddc42f084a
Revises: 157647760123
Create Date: 2026-04-25 21:38:23.303823

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "10ddc42f084a"
down_revision = "157647760123"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_context().dialect.name == "sqlite":
        with op.batch_alter_table("character_iteration_item_instance_modifiers") as batch_op:
            batch_op.alter_column(
                "iteration_id",
                existing_type=sa.CHAR(length=32),
                type_=sa.String(),
                existing_nullable=False,
            )
    else:
        op.alter_column(
            "character_iteration_item_instance_modifiers",
            "iteration_id",
            existing_type=sa.CHAR(length=32),
            type_=sa.String(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_context().dialect.name == "sqlite":
        with op.batch_alter_table("character_iteration_item_instance_modifiers") as batch_op:
            batch_op.alter_column(
                "iteration_id",
                existing_type=sa.String(),
                type_=sa.CHAR(length=32),
                existing_nullable=False,
            )
    else:
        op.alter_column(
            "character_iteration_item_instance_modifiers",
            "iteration_id",
            existing_type=sa.String(),
            type_=sa.CHAR(length=32),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
