"""add character_session_output table

Revision ID: 4d00544baa8e
Revises: c9fe37b6f17d
Create Date: 2026-04-11 21:56:38.887707

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4d00544baa8e"
down_revision = "c9fe37b6f17d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character_session_output",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("iteration_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("content_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["iteration_id"],
            ["character_iterations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_character_session_output_iteration_id"), "character_session_output", ["iteration_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_character_session_output_iteration_id"), table_name="character_session_output")
    op.drop_table("character_session_output")
    # ### end Alembic commands ###
