"""add ingame time tables

Revision ID: 50db8ddc0649
Revises: 259483ce21e3
Create Date: 2026-04-05 13:12:18.916763

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "50db8ddc0649"
down_revision = "259483ce21e3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character_iteration_era_state",
        sa.Column("iteration_id", sa.Uuid(), nullable=False),
        sa.Column("era_name", sa.String(), nullable=False),
        sa.Column("started_at_game_ticks", sa.BigInteger(), nullable=True),
        sa.Column("ended_at_game_ticks", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["iteration_id"],
            ["character_iterations.id"],
        ),
        sa.PrimaryKeyConstraint("iteration_id", "era_name"),
    )
    op.add_column(
        "character_iteration_adventure_state", sa.Column("last_completed_at_ticks", sa.BigInteger(), nullable=True)
    )
    op.drop_column("character_iteration_adventure_state", "last_completed_at_total")
    op.add_column(
        "character_iterations",
        sa.Column("internal_ticks", sa.BigInteger(), nullable=False, server_default="0"),
    )
    op.add_column(
        "character_iterations",
        sa.Column("game_ticks", sa.BigInteger(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("character_iterations", "game_ticks")
    op.drop_column("character_iterations", "internal_ticks")
    op.add_column(
        "character_iteration_adventure_state", sa.Column("last_completed_at_total", sa.INTEGER(), nullable=True)
    )
    op.drop_column("character_iteration_adventure_state", "last_completed_at_ticks")
    op.drop_table("character_iteration_era_state")
    # ### end Alembic commands ###
