"""add persistence schema

Revision ID: 54ce9666dd28
Revises:
Create Date: 2026-03-29 09:01:24.732776

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "54ce9666dd28"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_key", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_key"),
    )
    op.create_table(
        "characters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_character_user_name"),
    )
    op.create_table(
        "character_iterations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("character_id", sa.Uuid(), nullable=False),
        sa.Column("iteration", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("xp", sa.Integer(), nullable=False),
        sa.Column("hp", sa.Integer(), nullable=False),
        sa.Column("max_hp", sa.Integer(), nullable=False),
        sa.Column("character_class", sa.String(), nullable=True),
        sa.Column("current_location", sa.String(), nullable=True),
        sa.Column("adventure_ref", sa.String(), nullable=True),
        sa.Column("adventure_step_index", sa.Integer(), nullable=True),
        sa.Column("adventure_step_state", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("session_token", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("character_id", "iteration", name="uq_character_iteration"),
    )
    op.create_index(
        "uq_active_iteration_per_character",
        "character_iterations",
        ["character_id"],
        unique=True,
        postgresql_where=sa.text("is_active IS TRUE"),
        sqlite_where=sa.text("is_active = 1"),
    )
    op.create_table(
        "character_iteration_equipment",
        sa.Column("iteration_id", sa.Uuid(), nullable=False),
        sa.Column("slot", sa.String(), nullable=False),
        sa.Column("item_ref", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["iteration_id"],
            ["character_iterations.id"],
        ),
        sa.PrimaryKeyConstraint("iteration_id", "slot"),
    )
    op.create_table(
        "character_iteration_inventory",
        sa.Column("iteration_id", sa.Uuid(), nullable=False),
        sa.Column("item_ref", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["iteration_id"],
            ["character_iterations.id"],
        ),
        sa.PrimaryKeyConstraint("iteration_id", "item_ref"),
    )
    op.create_table(
        "character_iteration_milestones",
        sa.Column("iteration_id", sa.Uuid(), nullable=False),
        sa.Column("milestone_ref", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["iteration_id"],
            ["character_iterations.id"],
        ),
        sa.PrimaryKeyConstraint("iteration_id", "milestone_ref"),
    )
    op.create_table(
        "character_iteration_quests",
        sa.Column("iteration_id", sa.Uuid(), nullable=False),
        sa.Column("quest_ref", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("stage", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["iteration_id"],
            ["character_iterations.id"],
        ),
        sa.PrimaryKeyConstraint("iteration_id", "quest_ref"),
    )
    op.create_table(
        "character_iteration_stat_values",
        sa.Column("iteration_id", sa.Uuid(), nullable=False),
        sa.Column("stat_name", sa.String(), nullable=False),
        sa.Column("stat_value", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["iteration_id"],
            ["character_iterations.id"],
        ),
        sa.PrimaryKeyConstraint("iteration_id", "stat_name"),
    )
    op.create_table(
        "character_iteration_statistics",
        sa.Column("iteration_id", sa.Uuid(), nullable=False),
        sa.Column("stat_type", sa.String(), nullable=False),
        sa.Column("entity_ref", sa.String(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["iteration_id"],
            ["character_iterations.id"],
        ),
        sa.PrimaryKeyConstraint("iteration_id", "stat_type", "entity_ref"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("character_iteration_statistics")
    op.drop_table("character_iteration_stat_values")
    op.drop_table("character_iteration_quests")
    op.drop_table("character_iteration_milestones")
    op.drop_table("character_iteration_inventory")
    op.drop_table("character_iteration_equipment")
    op.drop_index(
        "uq_active_iteration_per_character",
        table_name="character_iterations",
        postgresql_where=sa.text("is_active IS TRUE"),
        sqlite_where=sa.text("is_active = 1"),
    )
    op.drop_table("character_iterations")
    op.drop_table("characters")
    op.drop_table("users")
    # ### end Alembic commands ###
