"""tick-anchored-state-refactor

Revision ID: 702eb8ecb200
Revises: 840b0f8aab05
Create Date: 2026-04-07 18:55:17.994997

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "702eb8ecb200"
down_revision = "840b0f8aab05"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "character_iteration_adventure_state", sa.Column("last_completed_real_ts", sa.BigInteger(), nullable=True)
    )
    op.add_column(
        "character_iteration_adventure_state", sa.Column("last_completed_game_ticks", sa.BigInteger(), nullable=True)
    )
    op.drop_column("character_iteration_adventure_state", "last_completed_on")
    op.add_column(
        "character_iteration_milestones",
        sa.Column("grant_tick", sa.BigInteger(), nullable=False, server_default="0"),
    )
    op.add_column(
        "character_iteration_milestones",
        sa.Column("grant_timestamp", sa.BigInteger(), nullable=False, server_default="0"),
    )
    op.add_column(
        "character_iteration_skill_cooldowns",
        sa.Column("tick_expiry", sa.BigInteger(), nullable=False, server_default="0"),
    )
    op.add_column(
        "character_iteration_skill_cooldowns",
        sa.Column("real_expiry", sa.BigInteger(), nullable=False, server_default="0"),
    )
    op.drop_column("character_iteration_skill_cooldowns", "cooldown_remaining")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("character_iteration_skill_cooldowns", sa.Column("cooldown_remaining", sa.INTEGER(), nullable=False))
    op.drop_column("character_iteration_skill_cooldowns", "real_expiry")
    op.drop_column("character_iteration_skill_cooldowns", "tick_expiry")
    op.drop_column("character_iteration_milestones", "grant_timestamp")
    op.drop_column("character_iteration_milestones", "grant_tick")
    op.add_column("character_iteration_adventure_state", sa.Column("last_completed_on", sa.VARCHAR(), nullable=True))
    op.drop_column("character_iteration_adventure_state", "last_completed_game_ticks")
    op.drop_column("character_iteration_adventure_state", "last_completed_real_ts")
    # ### end Alembic commands ###
