"""add title and pronoun_set to characters

Revision ID: 838f5ad54e6c
Revises: fef7c4caf398
Create Date: 2026-04-01 19:17:22.687702

"""

# revision identifiers, used by Alembic.
revision = "838f5ad54e6c"
down_revision = "fef7c4caf398"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
