"""add pending triggers table

Revision ID: 840b0f8aab05
Revises: 50db8ddc0649
Create Date: 2026-04-05 18:49:00.099845

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "840b0f8aab05"
down_revision = "50db8ddc0649"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character_iteration_pending_triggers",
        sa.Column("iteration_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("trigger_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["iteration_id"],
            ["character_iterations.id"],
        ),
        sa.PrimaryKeyConstraint("iteration_id", "position"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("character_iteration_pending_triggers")
    # ### end Alembic commands ###
