"""add_auth_audit_log_table

Revision ID: 8cb42c2142c2
Revises: 4d00544baa8e
Create Date: 2026-04-12 17:31:07.739526

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8cb42c2142c2"
down_revision = "4d00544baa8e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_auth_audit_log_created_at", "auth_audit_log", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_auth_audit_log_created_at", table_name="auth_audit_log")
    op.drop_table("auth_audit_log")
    # ### end Alembic commands ###
