"""remove_hardcoded_progression_columns

Revision ID: 97bbf20a2043
Revises: 702eb8ecb200
Create Date: 2026-04-08 17:51:47.280658

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "97bbf20a2043"
down_revision = "702eb8ecb200"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("character_iterations", "hp")
    op.drop_column("character_iterations", "xp")
    op.drop_column("character_iterations", "max_hp")
    op.drop_column("character_iterations", "level")
    # ### end Alembic commands ###


def downgrade() -> None:
    # Re-add the four columns; made nullable so existing rows are not rejected.
    op.add_column("character_iterations", sa.Column("level", sa.INTEGER(), nullable=True))
    op.add_column("character_iterations", sa.Column("max_hp", sa.INTEGER(), nullable=True))
    op.add_column("character_iterations", sa.Column("xp", sa.INTEGER(), nullable=True))
    op.add_column("character_iterations", sa.Column("hp", sa.INTEGER(), nullable=True))
