"""add title and pronoun_set to character iterations

Revision ID: b39a892757e1
Revises: 838f5ad54e6c
Create Date: 2026-04-01 19:19:26.582148

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b39a892757e1"
down_revision = "838f5ad54e6c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "character_iterations",
        sa.Column("title", sa.String(), nullable=False, server_default=""),
    )
    op.add_column(
        "character_iterations",
        sa.Column("pronoun_set", sa.String(), nullable=False, server_default="they_them"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("character_iterations", "pronoun_set")
    op.drop_column("character_iterations", "title")
    # ### end Alembic commands ###
