"""Add game_name field to characters table for multi-game support

Revision ID: c05a68726c2e
Revises: d32ff002b8aa
Create Date: 2026-03-29 13:29:07.327064

"""

# revision identifiers, used by Alembic.
revision = "c05a68726c2e"
down_revision = "d32ff002b8aa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
