"""add session_token_acquired_at to character_iterations

Revision ID: c9fe37b6f17d
Revises: d536049d79a9
Create Date: 2026-04-11 21:55:49.740148

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c9fe37b6f17d"
down_revision = "d536049d79a9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "character_iterations", sa.Column("session_token_acquired_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("character_iterations", "session_token_acquired_at")
    # ### end Alembic commands ###
