"""add_item_instances_tables_and_update_equipment_schema

Revision ID: d4c9cbe28338
Revises: c05a68726c2e
Create Date: 2026-03-29 18:34:01.680780

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d4c9cbe28338"
down_revision = "c05a68726c2e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character_iteration_item_instances",
        sa.Column("iteration_id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.String(), nullable=False),
        sa.Column("item_ref", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["iteration_id"],
            ["character_iterations.id"],
        ),
        sa.PrimaryKeyConstraint("iteration_id", "instance_id"),
    )
    op.create_table(
        "character_iteration_item_instance_modifiers",
        sa.Column("iteration_id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.String(), nullable=False),
        sa.Column("stat", sa.String(), nullable=False),
        sa.Column("amount", sa.REAL(), nullable=False),
        sa.ForeignKeyConstraint(
            ["iteration_id", "instance_id"],
            ["character_iteration_item_instances.iteration_id", "character_iteration_item_instances.instance_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("iteration_id", "instance_id", "stat"),
    )
    op.add_column("character_iteration_equipment", sa.Column("instance_id", sa.String(), nullable=False))
    op.drop_column("character_iteration_equipment", "item_ref")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("character_iteration_equipment", sa.Column("item_ref", sa.VARCHAR(), nullable=False))
    op.drop_column("character_iteration_equipment", "instance_id")
    op.drop_table("character_iteration_item_instance_modifiers")
    op.drop_table("character_iteration_item_instances")
    # ### end Alembic commands ###
