"""remove title from character iterations

Revision ID: d734190494ea
Revises: b39a892757e1
Create Date: 2026-04-01 20:01:39.359121

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d734190494ea"
down_revision = "b39a892757e1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("character_iterations", "title")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "character_iterations", sa.Column("title", sa.VARCHAR(), server_default=sa.text("('')"), nullable=False)
    )
    # ### end Alembic commands ###
