"""add skill system tables

Revision ID: fef7c4caf398
Revises: d3057a86660a
Create Date: 2026-03-31 17:31:49.899943

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fef7c4caf398"
down_revision = "d3057a86660a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character_iteration_skill_cooldowns",
        sa.Column("iteration_id", sa.Uuid(), nullable=False),
        sa.Column("skill_ref", sa.String(), nullable=False),
        sa.Column("cooldown_remaining", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["iteration_id"],
            ["character_iterations.id"],
        ),
        sa.PrimaryKeyConstraint("iteration_id", "skill_ref"),
    )
    op.create_table(
        "character_iteration_skills",
        sa.Column("iteration_id", sa.Uuid(), nullable=False),
        sa.Column("skill_ref", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["iteration_id"],
            ["character_iterations.id"],
        ),
        sa.PrimaryKeyConstraint("iteration_id", "skill_ref"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("character_iteration_skills")
    op.drop_table("character_iteration_skill_cooldowns")
    # ### end Alembic commands ###
